// Cookie helpers
function setCookie(name, value, days) {
    const expires = new Date(Date.now() + days * 864e5).toUTCString();
    document.cookie = name + '=' + encodeURIComponent(value) + ';expires=' + expires + ';path=/;SameSite=Lax';
}

function getCookie(name) {
    const match = document.cookie.match(new RegExp('(?:^|; )' + name + '=([^;]*)'));
    return match ? decodeURIComponent(match[1]) : null;
}

function clearCookie(name) {
    document.cookie = name + '=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;SameSite=Lax';
}

// Token model
// ------------
// webSession            — long-lived per-browser session credential. Stored
//                         in localStorage / cookie. Sent as Bearer on every
//                         API call. Issued by /pingclaw/auth/social or /auth/web-login.
// apiKeyPlaintext       — in-memory ONLY. Holds the api_key plaintext from
//                         the moment the user clicks "Rotate API Key" until
//                         the page is reloaded. Never persisted.
// hasApiKey             — boolean from GET /pingclaw/auth/me telling us
//                         whether the server has an active api_key. Drives
//                         the **** vs "Generate" rendering.

function saveSession() {
    if (webSession) {
        localStorage.setItem('web_session', webSession);
        setCookie('web_session', webSession, 90);
    }
}

function clearSession() {
    localStorage.removeItem('web_session');
    clearCookie('web_session');
    // Also clean up any leftover state from the previous token model so
    // nothing stale leaks across sessions.
    localStorage.removeItem('api_key');
    localStorage.removeItem('pairing_token');
    clearCookie('api_key');
    clearCookie('pairing_token');
}

let webSession = localStorage.getItem('web_session') || getCookie('web_session');
if (webSession && !localStorage.getItem('web_session')) {
    localStorage.setItem('web_session', webSession);
}

let apiKeyPlaintext = null;
let hasApiKey = false;
let webhookURL = null;
let webhookSecret = null;
let mcpTarget = localStorage.getItem('mcp_target') || 'code'; // 'code' | 'desktop'

// Platform detection
const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent);
const isAndroid = /Android/.test(navigator.userAgent);
const platformLabel = isIOS ? 'iOS App' : isAndroid ? 'Android App' : '';

// Init
document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('.platform-tag').forEach(el => {
        if (platformLabel) {
            el.textContent = platformLabel;
        } else {
            el.style.display = 'none';
        }
    });

    document.querySelectorAll('.ios-only').forEach(el => {
        el.style.display = isIOS ? '' : 'none';
    });

    // Check for a ?webcode= parameter (generated by the iOS app's
    // "Open Dashboard" button). If present, auto-sign-in and go straight
    // to the dashboard — no manual code entry needed.
    const params = new URLSearchParams(window.location.search);
    const autoCode = params.get('webcode');
    if (autoCode) {
        // Strip the code from the URL so a refresh doesn't re-submit.
        history.replaceState(null, '', window.location.pathname);
        autoWebLogin(autoCode);
    } else if (webSession) {
        showSection('dashboard');
    } else {
        showSection('landing');
    }
    updateHeaderBtn();
});

// Auto-submit a web login code (from the URL query string).
async function autoWebLogin(code) {
    try {
        const res = await fetch('/pingclaw/auth/web-login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ code }),
        });
        const data = await res.json();
        if (res.ok && data.web_session) {
            webSession = data.web_session;
            saveSession();
            showSection('dashboard');
            return;
        }
    } catch (err) { /* fall through */ }
    // Code expired or invalid — show the normal auth page.
    showSection('landing');
}

// Navigation
let locationPollInterval = null;

function showSection(id) {
    document.querySelectorAll('main > section').forEach(s => s.hidden = true);
    document.getElementById(id).hidden = false;
    updateHeaderBtn();

    if (id === 'dashboard') {
        loadDashboard();
        startLocationPolling();
    } else if (id === 'auth') {
        // Initialise social sign-in SDK buttons (idempotent).
        setTimeout(initSocialAuth, 100);
        stopLocationPolling();
    } else {
        stopLocationPolling();
    }
}

function startLocationPolling() {
    stopLocationPolling();
    locationPollInterval = setInterval(fetchLocation, 10000);
}

function stopLocationPolling() {
    if (locationPollInterval) {
        clearInterval(locationPollInterval);
        locationPollInterval = null;
    }
}

function handleHeaderBtn() {
    if (webSession) {
        logout();
    } else {
        showSection('auth');
    }
}

function updateHeaderBtn() {
    document.querySelectorAll('.header-btn').forEach(btn => {
        if (webSession) {
            btn.textContent = 'Sign out';
            btn.className = 'pc-btn-ghost pc-btn-sm header-btn';
        } else {
            btn.textContent = 'Sign in';
            btn.className = 'pc-btn-primary pc-btn-sm header-btn';
        }
    });
}

// --- Social auth ---

// Called once when the auth section becomes visible. Initialises the
// Google SDK (but doesn't render their button — we use our own styled
// one). Apple uses a plain HTML button + AppleID.auth.signIn().
// Idempotent — safe to call on every show.
let googleInitialised = false;
function initSocialAuth() {
    if (googleInitialised) return;
    if (typeof google !== 'undefined' && google.accounts) {
        const clientId = document.querySelector('meta[name="google-client-id"]')?.content || '';
        if (clientId) {
            google.accounts.id.initialize({
                client_id: clientId,
                callback: function(response) {
                    handleSocialToken('google', response.credential);
                },
            });
            googleInitialised = true;
        }
    }
}

// Google Sign in — triggered by our styled button's onclick.
function googleSignIn() {
    if (!googleInitialised) {
        initSocialAuth();
    }
    if (googleInitialised) {
        google.accounts.id.prompt();
    } else {
        showAuthError('Google Sign-In is loading. Try again in a moment.');
    }
}

// Apple Sign in — triggered by our styled button's onclick.
async function appleSignIn() {
    if (typeof AppleID === 'undefined') {
        showAuthError('Apple Sign-In is loading. Try again in a moment.');
        return;
    }
    try {
        AppleID.auth.init({
            clientId: 'me.pingclaw.web',
            scope: 'email',
            redirectURI: window.location.origin,
            usePopup: true,
        });
        const data = await AppleID.auth.signIn();
        if (data.authorization && data.authorization.id_token) {
            handleSocialToken('apple', data.authorization.id_token);
        }
    } catch (err) {
        if (err.error !== 'popup_closed_by_user') {
            showAuthError('Apple sign-in failed.');
        }
    }
}

function showAuthError(msg) {
    const el = document.getElementById('web-code-error');
    if (el) { el.textContent = msg; el.hidden = false; }
}

// Sends the provider's id_token to the server, gets back a web_session.
async function handleSocialToken(provider, idToken) {
    const errorEl = document.getElementById('web-code-error');
    if (errorEl) errorEl.hidden = true;

    try {
        const res = await fetch('/pingclaw/auth/social', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ provider, id_token: idToken, client: 'web' }),
        });
        const data = await res.json();
        if (!res.ok) {
            if (errorEl) {
                errorEl.textContent = data.error || 'Sign-in failed';
                errorEl.hidden = false;
            }
            return;
        }
        webSession = data.web_session;
        saveSession();
        showSection('dashboard');
    } catch (err) {
        if (errorEl) {
            errorEl.textContent = 'Network error. Is the server running?';
            errorEl.hidden = false;
        }
    }
}

// Signs in via a code generated on the phone (POST /pingclaw/auth/web-login).
async function webLogin() {
    const input = document.getElementById('web-code-input');
    const errorEl = document.getElementById('web-code-error');
    if (errorEl) errorEl.hidden = true;

    const code = (input?.value || '').trim().toUpperCase();
    if (!code) {
        if (errorEl) {
            errorEl.textContent = 'Enter the code from your phone.';
            errorEl.hidden = false;
        }
        return;
    }

    try {
        const res = await fetch('/pingclaw/auth/web-login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ code }),
        });
        const data = await res.json();
        if (!res.ok) {
            if (errorEl) {
                errorEl.textContent = data.error || 'Invalid or expired code';
                errorEl.hidden = false;
            }
            return;
        }
        webSession = data.web_session;
        saveSession();
        if (input) input.value = '';
        showSection('dashboard');
    } catch (err) {
        if (errorEl) {
            errorEl.textContent = 'Network error. Is the server running?';
            errorEl.hidden = false;
        }
    }
}

function logout() {
    webSession = null;
    apiKeyPlaintext = null;
    hasApiKey = false;
    webhookURL = null;
    webhookSecret = null;
    clearSession();
    showSection('landing');
}

// Dashboard
async function loadDashboard() {
    // Reset the "View my data" panel so it starts collapsed on every
    // fresh entry into the dashboard (sign-in, page reload, etc).
    const myDataWrap = document.getElementById('my-data-wrap');
    const myDataDisplay = document.getElementById('my-data-display');
    const myDataToggle = document.getElementById('my-data-toggle');
    if (myDataWrap) myDataWrap.style.display = 'none';
    if (myDataDisplay) {
        myDataDisplay.textContent = '';
        delete myDataDisplay.dataset.loaded;
    }
    if (myDataToggle) myDataToggle.textContent = 'View my data';

    // Load the ChatGPT setup content (always visible).
    loadSetupSubContent('chatgpt');

    // Render the webhook examples (always visible).
    const curlEl = document.getElementById('webhook-help-curl');
    if (curlEl) curlEl.textContent = renderWebhookCurl(window.location.origin);
    updateWebhookTokenExample();

    // Fetch token presence from the server. The dashboard needs to know
    // whether to show "**** • Rotate" or a "Generate" CTA, but the actual
    // plaintext values are never sent down by the server.
    try {
        const res = await fetch('/pingclaw/auth/me', {
            headers: { Authorization: 'Bearer ' + webSession },
        });
        if (res.status === 401) { logout(); return; }
        const data = await res.json();
        hasApiKey = !!data.has_api_key;
    } catch (err) {
        // Render anyway with whatever we know.
    }

    // Fetch the configured webhook (if any). Server returns plaintext URL
    // and secret because the user supplied them.
    try {
        const res = await fetch('/pingclaw/webhook', {
            headers: { Authorization: 'Bearer ' + webSession },
        });
        if (res.ok) {
            const data = await res.json();
            webhookURL = data.url || null;
            webhookSecret = data.webhook_secret || null;
        }
    } catch (err) { /* leave nulls */ }

    renderApiKey();
    renderMcpConfig();
    renderWebhook();
    fetchLocation();
}

function renderWebhook() {
    const setup = document.getElementById('webhook-setup');
    const configured = document.getElementById('webhook-configured');
    const urlInput = document.getElementById('webhook-url-display');
    const secretInput = document.getElementById('webhook-secret-display');
    if (!setup || !configured || !urlInput || !secretInput) return;

    if (webhookURL) {
        urlInput.value = webhookURL;
        secretInput.value = maskSecretTail(webhookSecret);
        configured.style.display = '';
        setup.style.display = 'none';
    } else {
        configured.style.display = 'none';
        setup.style.display = '';
    }
}

// Render only the last 4 characters of a secret, prefixed with bullets.
// The full value is still copyable via the Copy button.
function maskSecretTail(s) {
    if (!s) return '';
    const tail = s.length > 4 ? s.slice(-4) : s;
    return '\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022' + tail;
}

// Updates the webhook setup example with the real API key when available.
function updateWebhookTokenExample() {
    const el = document.getElementById('webhook-token-example');
    if (!el) return;
    const token = apiKeyPlaintext || 'ak_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    el.value = 'export PINGCLAW_TOKEN=' + token;
}

function renderWebhookCurl(origin) {
    return [
        'curl -X PUT ' + origin + '/pingclaw/webhook \\',
        '  -H "Authorization: Bearer $PINGCLAW_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{\"url\":\"https://your-receiver.example.com/location\",\"secret\":\"'\"$WEBHOOK_SECRET\"'\"}'",
    ].join('\n');
}

// Copies the value of the input that immediately precedes the clicked button.
function copyAdjacentInput(btn) {
    const input = btn.previousElementSibling;
    if (!input || input.tagName !== 'INPUT') return;
    copyToClipboard(input.value, btn);
}

function copyWebhookCurl(btn) {
    const pre = document.getElementById('webhook-help-curl');
    if (!pre || !pre.textContent) return;
    copyToClipboard(pre.textContent, btn);
}

async function testWebhook() {
    const status = document.getElementById('webhook-test-status');
    if (status) {
        status.style.display = '';
        status.style.color = 'var(--pc-text-3)';
        status.textContent = 'Sending';
    }
    try {
        const res = await fetch('/pingclaw/webhook/test', {
            method: 'POST',
            headers: { Authorization: 'Bearer ' + webSession },
        });
        const data = await res.json();
        if (!status) return;
        if (res.ok) {
            const loc = data.location;
            const locStr = loc ? loc.lat.toFixed(4) + ', ' + loc.lng.toFixed(4) : 'unknown';
            status.style.color = 'var(--pc-accent)';
            status.textContent = 'Delivered (HTTP ' + data.delivered_status + ') · location ' + locStr;
        } else {
            status.style.color = 'var(--pc-error)';
            status.textContent = 'Failed: ' + (data.error || 'unknown error');
        }
    } catch (err) {
        if (status) {
            status.style.color = 'var(--pc-error)';
            status.textContent = 'Network error';
        }
    }
}

async function deleteWebhook() {
    if (!confirm('Remove the registered webhook? PingClaw will stop forwarding location updates until a new one is registered.')) return;
    try {
        const res = await fetch('/pingclaw/webhook', {
            method: 'DELETE',
            headers: { Authorization: 'Bearer ' + webSession },
        });
        if (!res.ok) { alert('Failed to remove webhook'); return; }
        webhookURL = null;
        webhookSecret = null;
        renderWebhook();
    } catch (err) {
        alert('Network error');
    }
}

function copyWebhookField(which) {
    const text = which === 'url' ? webhookURL : webhookSecret;
    if (!text) return;
    copyToClipboard(text, event.target);
}

// Render a token field. Three possible states:
//   1. Plaintext in memory (just rotated this session) — show real value
//      with Copy / iOS deep-link / Rotate.
//   2. Server has a token but we don't have plaintext locally — show ●●●●
//      with Rotate (which warns it kicks the existing client).
//   3. Server has no token yet — show a single "Generate" CTA.
const MASK = '\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022';

function renderApiKey() {
    const input = document.getElementById('api-key-display');
    const inputRow = document.getElementById('api-key-input-row');
    const actions = document.getElementById('api-key-actions');
    const empty = document.getElementById('api-key-empty');
    const copyBtn = document.getElementById('api-key-copy');
    const rotateBtn = document.getElementById('api-key-rotate');
    if (!input || !inputRow || !actions || !empty || !copyBtn || !rotateBtn) return;

    if (apiKeyPlaintext) {
        input.value = apiKeyPlaintext;
        inputRow.style.display = '';
        actions.style.display = '';
        empty.style.display = 'none';
        copyBtn.style.display = '';
        rotateBtn.textContent = 'Rotate';
    } else if (hasApiKey) {
        input.value = MASK;
        inputRow.style.display = '';
        actions.style.display = '';
        empty.style.display = 'none';
        copyBtn.style.display = 'none';
        rotateBtn.textContent = 'Rotate';
    } else {
        inputRow.style.display = 'none';
        actions.style.display = 'none';
        empty.style.display = '';
    }
}

// MCP_TARGETS describes each supported client: the per-paste intro line
// and a builder that returns the JSON snippet to render.
//
// The shared HTTP shape is { type: 'http', url, headers } — most clients
// accept it under either `mcpServers` (Claude/Cursor/Windsurf) or
// `servers` (VS Code). Claude Desktop is the outlier: stdio-only, wrapped
// in `npx mcp-remote`. Zed uses its own `context_servers` key.
const MCP_TARGETS = {
    'code': {
        label: 'Claude Code',
        intro: 'Paste this into ~/.claude.json (under "projects".<your-project>) and reconnect.',
        build: (url, token) => ({
            mcpServers: { pingclaw: { type: 'http', url, headers: { Authorization: 'Bearer ' + token } } },
        }),
    },
    'desktop': {
        label: 'Claude Desktop',
        intro: 'Paste this into ~/Library/Application Support/Claude/claude_desktop_config.json. Claude Desktop runs npx to bridge HTTP to its stdio transport.',
        build: (url, token) => ({
            mcpServers: {
                pingclaw: {
                    command: 'npx',
                    args: ['-y', 'mcp-remote', url, '--header', 'Authorization:Bearer ' + token],
                },
            },
        }),
    },
    'vscode': {
        label: 'VS Code',
        intro: 'Paste this into .vscode/mcp.json (workspace) or open the Command Palette → "MCP: Open User Configuration".',
        build: (url, token) => ({
            servers: { pingclaw: { type: 'http', url, headers: { Authorization: 'Bearer ' + token } } },
        }),
    },
    'cursor': {
        label: 'Cursor',
        intro: 'Paste this into ~/.cursor/mcp.json (or the workspace .cursor/mcp.json).',
        build: (url, token) => ({
            mcpServers: { pingclaw: { type: 'http', url, headers: { Authorization: 'Bearer ' + token } } },
        }),
    },
    'windsurf': {
        label: 'Windsurf',
        intro: 'Paste this into ~/.codeium/windsurf/mcp_config.json.',
        build: (url, token) => ({
            mcpServers: { pingclaw: { type: 'http', url, headers: { Authorization: 'Bearer ' + token } } },
        }),
    },
    'zed': {
        label: 'Zed',
        intro: 'Paste this into your Zed settings.json under "context_servers".',
        build: (url, token) => ({
            context_servers: { pingclaw: { type: 'http', url, headers: { Authorization: 'Bearer ' + token } } },
        }),
    },
};

function setMcpTarget(target) {
    mcpTarget = MCP_TARGETS[target] ? target : 'code';
    localStorage.setItem('mcp_target', mcpTarget);
    syncMcpTargetSelect();
    renderMcpConfig();
}

function syncMcpTargetSelect() {
    const sel = document.getElementById('mcp-target-select');
    if (sel && sel.value !== mcpTarget) sel.value = mcpTarget;
}

function renderMcpConfig() {
    const block = document.getElementById('claude-config');
    const copyBtn = document.getElementById('mcp-config-copy');
    const hint = document.getElementById('mcp-config-hint');
    const intro = document.getElementById('mcp-config-intro');
    const picker = document.getElementById('mcp-target-picker');
    if (!block || !copyBtn || !hint || !intro) return;

    if (hasApiKey) {
        const tokenDisplay = apiKeyPlaintext || MASK;
        const url = window.location.origin + '/pingclaw/mcp';
        const t = MCP_TARGETS[mcpTarget] || MCP_TARGETS['code'];

        intro.textContent = t.intro;
        block.textContent = JSON.stringify(t.build(url, tokenDisplay), null, 2);
        block.style.display = '';
        intro.style.display = '';
        copyBtn.style.display = '';
        if (picker) picker.style.display = '';
        syncMcpTargetSelect();
        if (apiKeyPlaintext) {
            hint.style.display = 'none';
        } else {
            hint.style.display = '';
            hint.textContent = 'Click Rotate next to your API Key to reveal the full token before copying.';
        }
    } else {
        block.style.display = 'none';
        copyBtn.style.display = 'none';
        intro.style.display = 'none';
        if (picker) picker.style.display = 'none';
        hint.style.display = '';
        hint.textContent = 'Generate an API Key above to create your MCP config.';
    }
}

// Loads rendered markdown from /setup/<name>.html into the matching div.
async function loadSetupSubContent(name) {
    const el = document.getElementById('setup-' + name + '-content');
    if (!el || el.dataset.loaded === '1') return;
    try {
        const res = await fetch('/setup/' + name + '.html');
        if (!res.ok) return;
        el.innerHTML = await res.text();
        el.dataset.loaded = '1';
    } catch (err) { /* leave empty if fetch fails — non-critical */ }
}

async function fetchLocation() {
    const el = document.getElementById('location-status');
    if (!el.dataset.loaded) el.textContent = 'Locating';

    try {
        const res = await fetch('/pingclaw/location', {
            headers: { Authorization: 'Bearer ' + webSession },
        });
        if (res.status === 401) {
            el.textContent = 'Session expired. Signing out.';
            setTimeout(logout, 1500);
            return;
        }
        const data = await res.json();
        if (data.status === 'no_location') {
            el.innerHTML = 'Open PingClaw on your phone to start sharing your location with your agent.';
            return;
        }
        const loc = data.location;
        const serverNow = new Date(data.server_time).getTime();
        const locationTime = new Date(data.timestamp).getTime();
        const age = Math.max(0, Math.round((serverNow - locationTime) / 1000));
        const ageStr = age < 10 ? 'Updated just now'
            : age < 60 ? 'Updated ' + age + 's ago'
            : age < 3600 ? 'Updated ' + Math.round(age / 60) + 'm ago'
            : age < 86400 ? 'Updated ' + Math.round(age / 3600) + 'h ago'
            : 'Updated ' + Math.round(age / 86400) + 'd ago';
        const mapsUrl = isIOS
            ? 'maps://?q=' + loc.lat + ',' + loc.lng
            : 'https://www.google.com/maps?q=' + loc.lat + ',' + loc.lng;
        const latStr = formatCoord(loc.lat, true);
        const lngStr = formatCoord(loc.lng, false);
        const acc = Math.round(loc.accuracy_metres);
        const activity = data.activity || 'Located';
        el.innerHTML =
            '<div class="pc-location-readout" style="border:none; padding:0; background:transparent;">' +
                '<div class="pc-location-label">' + escapeHtml(activity) + '</div>' +
                '<div class="pc-location-coords">' +
                    '<span>' + latStr + '</span>' +
                    '<span class="pc-location-sep"> · </span>' +
                    '<span>' + lngStr + '</span>' +
                '</div>' +
                '<div class="pc-location-accuracy">± ' + acc + 'm · ' + ageStr + '</div>' +
            '</div>' +
            '<div style="display:flex;justify-content:flex-end;margin-top:16px;">' +
                '<a href="' + mapsUrl + '" target="_blank" class="pc-btn-ghost pc-btn-sm">Show map</a>' +
            '</div>';
        el.dataset.loaded = '1';
    } catch (err) {
        el.textContent = 'Location unavailable.';
    }
}

function formatCoord(value, isLat) {
    const hemi = isLat ? (value >= 0 ? 'N' : 'S') : (value >= 0 ? 'E' : 'W');
    return Math.abs(value).toFixed(4) + '° ' + hemi;
}

function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, c => ({
        '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;',
    }[c]));
}

async function rotateAPIKey() {
    if (hasApiKey) {
        if (!confirm('Rotate your API Key? Your MCP agent config will stop working until you paste in the new key.')) return;
    }
    try {
        const res = await fetch('/pingclaw/auth/rotate-api-key', {
            method: 'POST',
            headers: { Authorization: 'Bearer ' + webSession },
        });
        const data = await res.json();
        if (!res.ok) { alert(data.error || 'Failed to rotate'); return; }
        apiKeyPlaintext = data.api_key;
        hasApiKey = true;
        renderApiKey();
        renderMcpConfig();
        updateWebhookTokenExample();
        flashField('api-key-display');
    } catch (err) {
        alert('Network error');
    }
}

function flashField(id) {
    const el = document.getElementById(id);
    if (!el) return;
    el.style.transition = 'background-color 0.3s, border-color 0.3s';
    el.style.backgroundColor = 'var(--pc-accent-bg)';
    el.style.borderColor = 'var(--pc-accent)';
    setTimeout(() => {
        el.style.backgroundColor = '';
        el.style.borderColor = '';
        setTimeout(() => el.style.transition = '', 500);
    }, 750);
}

async function viewMyData() {
    const wrap = document.getElementById('my-data-wrap');
    const display = document.getElementById('my-data-display');
    const toggle = document.getElementById('my-data-toggle');
    if (!wrap || !display) return;
    if (wrap.style.display !== 'none' && display.dataset.loaded === '1') {
        // Toggle off if already shown.
        wrap.style.display = 'none';
        if (toggle) toggle.textContent = 'View my data';
        return;
    }
    wrap.style.display = '';
    display.textContent = 'Loading…';
    if (toggle) toggle.textContent = 'Hide my data';
    try {
        const res = await fetch('/pingclaw/auth/data', {
            headers: { Authorization: 'Bearer ' + webSession },
        });
        const data = await res.json();
        if (!res.ok) {
            display.textContent = 'Failed: ' + (data.error || res.status);
            return;
        }
        display.textContent = JSON.stringify(data, null, 2);
        display.dataset.loaded = '1';
    } catch (err) {
        display.textContent = 'Network error';
    }
}

async function deleteAccount() {
    if (!confirm('Are you sure? This will permanently delete your account and all data.')) return;
    if (!confirm('This cannot be undone. Delete your account?')) return;
    try {
        const res = await fetch('/pingclaw/auth/account', {
            method: 'DELETE',
            headers: { Authorization: 'Bearer ' + webSession },
        });
        if (!res.ok) { alert('Failed to delete account'); return; }
        logout();
    } catch (err) {
        alert('Network error');
    }
}

function copyToken(type) {
    const text = apiKeyPlaintext;
    if (!text) return;
    copyToClipboard(text, event.target);
}

function copyConfig() {
    const text = document.getElementById('claude-config').textContent;
    if (!text) return;
    copyToClipboard(text, event.target);
}

function copyToClipboard(text, btn) {
    if (navigator.clipboard && window.isSecureContext) {
        navigator.clipboard.writeText(text).then(() => showCopied(btn));
    } else {
        const textarea = document.createElement('textarea');
        textarea.value = text;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.focus();
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        showCopied(btn);
    }
}

function showCopied(btn) {
    const original = btn.textContent;
    btn.textContent = 'Copied!';
    setTimeout(() => btn.textContent = original, 1500);
}

document.addEventListener('keydown', (e) => {
    if (e.key !== 'Enter') return;
    if (e.target.id === 'web-code-input') webLogin();
});
